// Seed data - Daftar Anggota Dharma Wanita Dinkes Asahan
// Auto-loads on first app visit if no data exists

export const seedAnggota = [
    // === ANGGOTA TERDAFTAR DI ABSENSI DW (1-57) - Istri PNS Aktif ===
    { nama: "Ny. dr. Elfitriani H. Hari Sapna", jabatan: "Ketua", kategori: "Istri PNS Aktif", noHp: "", alamat: "", status: "aktif", potongan: 65000 },
    { nama: "Ny. Juliana Fahrizal Pohan", jabatan: "Wakil Ketua", kategori: "Istri PNS Aktif", noHp: "", alamat: "", status: "aktif", potongan: 65000 },
    { nama: "Ny. dr. Noni Mariani Tumanggor Harles Ramdani Sinulingga", jabatan: "Sekretaris", kategori: "Istri PNS Aktif", noHp: "", alamat: "", status: "aktif", potongan: 65000 },
    { nama: "Ny. Sunarti Qamaruzzaman Zaini", jabatan: "Wakil Sekretaris", kategori: "Istri PNS Aktif", noHp: "", alamat: "", status: "aktif", potongan: 65000 },
    { nama: "Ny. Winda Ranji Azwar", jabatan: "Bendahara", kategori: "Istri PNS Aktif", noHp: "", alamat: "", status: "aktif", potongan: 65000 },
    { nama: "Ny. Suti Handayani Sukirno", jabatan: "Wakil Bendahara", kategori: "Istri PNS Aktif", noHp: "", alamat: "", status: "aktif", potongan: 65000 },
    { nama: "Ny. Indah Setiyanti Surya Hadisyah Putra", jabatan: "Ketua Bidang Pendidikan", kategori: "Istri PNS Aktif", noHp: "", alamat: "", status: "aktif", potongan: 65000 },
    { nama: "Ny. Ratna Dewi Harmein Harahap", jabatan: "Ketua Bidang Ekonomi", kategori: "Istri PNS Aktif", noHp: "", alamat: "", status: "aktif", potongan: 65000 },
    { nama: "Ny. Sri Zukhairina Mhd Sutan Fakhrizal", jabatan: "Ketua Bidang Sosial Budaya", kategori: "Istri PNS Aktif", noHp: "", alamat: "", status: "aktif", potongan: 65000 },
    { nama: "Ny. Titin Lusi Hariani Slamet Santoso", jabatan: "Wakil Ketua Bidang Pendidikan", kategori: "Istri PNS Aktif", noHp: "", alamat: "", status: "aktif", potongan: 65000 },
    { nama: "Ny. Tiodor Sagala Marolop Simanjuntak", jabatan: "Wakil Ketua Bidang Ekonomi", kategori: "Istri PNS Aktif", noHp: "", alamat: "", status: "aktif", potongan: 65000 },
    { nama: "Ny. Tika Tety Nirmansyah", jabatan: "Wakil Ketua Bidang Sosial Budaya", kategori: "Istri PNS Aktif", noHp: "", alamat: "", status: "aktif", potongan: 65000 },
    { nama: "Ny. Suwartini Syandra Syaputra", jabatan: "Sekretaris Bidang Pendidikan", kategori: "Istri PNS Aktif", noHp: "", alamat: "", status: "aktif", potongan: 65000 },
    { nama: "Ny. Mega Rosa Ernita Sebayang Elvin Irving Barus", jabatan: "Sekretaris Bidang Ekonomi", kategori: "Istri PNS Aktif", noHp: "", alamat: "", status: "aktif", potongan: 65000 },
    { nama: "Ny. Lisdawati Hidayat Nasution", jabatan: "Sekretaris Bidang Sosial Budaya", kategori: "Istri PNS Aktif", noHp: "", alamat: "", status: "aktif", potongan: 65000 },
    { nama: "Ny. dr. Citra Dewi Kesuma Rahmat Abdi Sinaga", jabatan: "Anggota Bidang Pendidikan", kategori: "Istri PNS Aktif", noHp: "", alamat: "", status: "aktif", potongan: 65000 },
    { nama: "Ny. Apridawanti Usman Hasibuan", jabatan: "Anggota Bidang Pendidikan", kategori: "Istri PNS Aktif", noHp: "", alamat: "", status: "aktif", potongan: 65000 },
    { nama: "Ny. Zahir Arfida Nasution Herman Fariadi", jabatan: "Anggota Bidang Pendidikan", kategori: "Istri PNS Aktif", noHp: "", alamat: "", status: "aktif", potongan: 65000 },
    { nama: "Ny. Irfan Arif Lubis", jabatan: "Anggota Bidang Pendidikan", kategori: "Istri PNS Aktif", noHp: "", alamat: "", status: "aktif", potongan: 65000 },
    { nama: "Ny. Hardiansyah Marpaung", jabatan: "Anggota Bidang Pendidikan", kategori: "Istri PNS Aktif", noHp: "", alamat: "", status: "aktif", potongan: 65000 },
    { nama: "Ny. Saiful Bahri", jabatan: "Anggota Bidang Pendidikan", kategori: "Istri PNS Aktif", noHp: "", alamat: "", status: "aktif", potongan: 65000 },
    { nama: "Ny. Adnan Tarigan", jabatan: "Anggota Bidang Pendidikan", kategori: "Istri PNS Aktif", noHp: "", alamat: "", status: "aktif", potongan: 65000 },
    { nama: "Ny. Maryati Jalaludin Marpaung", jabatan: "Anggota Bidang Pendidikan", kategori: "Istri PNS Aktif", noHp: "", alamat: "", status: "aktif", potongan: 65000 },
    { nama: "Ny. Abdul Karim Simangunsong", jabatan: "Anggota Bidang Pendidikan", kategori: "Istri PNS Aktif", noHp: "", alamat: "", status: "aktif", potongan: 65000 },
    { nama: "Ny. Adi Chandra Siahaan", jabatan: "Anggota Bidang Pendidikan", kategori: "Istri PNS Aktif", noHp: "", alamat: "", status: "aktif", potongan: 65000 },
    { nama: "Ny. Romasinta Butar-Butar Robin Lumbantobing", jabatan: "Anggota Bidang Pendidikan", kategori: "Istri PNS Aktif", noHp: "", alamat: "", status: "aktif", potongan: 65000 },
    { nama: "Ny. Sri Wati Yusnaidi", jabatan: "Anggota Bidang Pendidikan", kategori: "Istri PNS Aktif", noHp: "", alamat: "", status: "aktif", potongan: 65000 },
    { nama: "Ny. Sri Wahyuni Masudi", jabatan: "Anggota Bidang Pendidikan", kategori: "Istri PNS Aktif", noHp: "", alamat: "", status: "aktif", potongan: 65000 },
    { nama: "Ny. Meilani Sinuraya Eka Lau Jordan Ginting", jabatan: "Anggota Bidang Pendidikan", kategori: "Istri PNS Aktif", noHp: "", alamat: "", status: "aktif", potongan: 65000 },
    { nama: "Ny. Nurhayani Nasir", jabatan: "Anggota Bidang Pendidikan", kategori: "Istri PNS Aktif", noHp: "", alamat: "", status: "aktif", potongan: 65000 },
    { nama: "Ny. Dewi Pusparani Siregar Gunawan Sinaga", jabatan: "Anggota Bidang Pendidikan", kategori: "Istri PNS Aktif", noHp: "", alamat: "", status: "aktif", potongan: 65000 },
    { nama: "Ny. Legini Paidi", jabatan: "Anggota Bidang Pendidikan", kategori: "Istri PNS Aktif", noHp: "", alamat: "", status: "aktif", potongan: 65000 },
    { nama: "Ny. Elfrida Dedy Chaniago", jabatan: "Anggota Bidang Pendidikan", kategori: "Istri PNS Aktif", noHp: "", alamat: "", status: "aktif", potongan: 65000 },
    { nama: "Ny. Lilis Aminudin Marpaung", jabatan: "Anggota Bidang Ekonomi", kategori: "Istri PNS Aktif", noHp: "", alamat: "", status: "aktif", potongan: 65000 },
    { nama: "Ny. Nurmi Nainggolan Kartiman Togatorop", jabatan: "Anggota Bidang Ekonomi", kategori: "Istri PNS Aktif", noHp: "", alamat: "", status: "aktif", potongan: 65000 },
    { nama: "Ny. Tiolina Asri Kurniawan", jabatan: "Anggota Bidang Ekonomi", kategori: "Istri PNS Aktif", noHp: "", alamat: "", status: "aktif", potongan: 65000 },
    { nama: "Ny. Nurazizah Malisi Sinaga", jabatan: "Anggota Bidang Ekonomi", kategori: "Istri PNS Aktif", noHp: "", alamat: "", status: "aktif", potongan: 65000 },
    { nama: "Ny. Santi Peronika Br. Siringo-Ringo Hottua Sipahutar", jabatan: "Anggota Bidang Ekonomi", kategori: "Istri PNS Aktif", noHp: "", alamat: "", status: "aktif", potongan: 65000 },
    { nama: "Ny. Nespita Ilhamsyah Putra", jabatan: "Anggota Bidang Ekonomi", kategori: "Istri PNS Aktif", noHp: "", alamat: "", status: "aktif", potongan: 65000 },
    { nama: "Ny. Herry Lesmono Wijaya", jabatan: "Anggota Bidang Ekonomi", kategori: "Istri PNS Aktif", noHp: "", alamat: "", status: "aktif", potongan: 65000 },
    { nama: "Ny. Nurlela Rajali Sirait", jabatan: "Anggota Bidang Ekonomi", kategori: "Istri PNS Aktif", noHp: "", alamat: "", status: "aktif", potongan: 65000 },
    { nama: "Ny. Ahmad Affandi Siregar", jabatan: "Anggota Bidang Ekonomi", kategori: "Istri PNS Aktif", noHp: "", alamat: "", status: "aktif", potongan: 65000 },
    { nama: "Ny. Suherlina Amran Sitorus", jabatan: "Anggota Bidang Ekonomi", kategori: "Istri PNS Aktif", noHp: "", alamat: "", status: "aktif", potongan: 65000 },
    { nama: "Ny. Christy Togu Pangihutan Oktavianus Togatorop", jabatan: "Anggota Bidang Ekonomi", kategori: "Istri PNS Aktif", noHp: "", alamat: "", status: "aktif", potongan: 65000 },
    { nama: "Ny. Ida Hanum Idamanta Karo Karo", jabatan: "Anggota Bidang Ekonomi", kategori: "Istri PNS Aktif", noHp: "", alamat: "", status: "aktif", potongan: 65000 },
    { nama: "Ny. Henny Purwanty Budi", jabatan: "Anggota Bidang Ekonomi", kategori: "Istri PNS Aktif", noHp: "", alamat: "", status: "aktif", potongan: 65000 },
    { nama: "Ny. Nina Afsari Simangunsong Budi Dermawan", jabatan: "Anggota Bidang Ekonomi", kategori: "Istri PNS Aktif", noHp: "", alamat: "", status: "aktif", potongan: 65000 },
    { nama: "Ny. Cik Rahmiana Heru Sulistyo", jabatan: "Anggota Bidang Ekonomi", kategori: "Istri PNS Aktif", noHp: "", alamat: "", status: "aktif", potongan: 65000 },
    { nama: "Ny. Mirna Yanti Gurning Dedi Irwadi Butar-Butar", jabatan: "Anggota Bidang Ekonomi", kategori: "Istri PNS Aktif", noHp: "", alamat: "", status: "aktif", potongan: 65000 },
    { nama: "Ny. Juriati Budi Purba", jabatan: "Anggota Bidang Ekonomi", kategori: "Istri PNS Aktif", noHp: "", alamat: "", status: "aktif", potongan: 65000 },
    { nama: "Ny. Supiyanto", jabatan: "Anggota Bidang Sosial Budaya", kategori: "Istri PNS Aktif", noHp: "", alamat: "", status: "aktif", potongan: 65000 },
    { nama: "Ny. Rudi Nasution", jabatan: "Anggota Bidang Sosial Budaya", kategori: "Istri PNS Aktif", noHp: "", alamat: "", status: "aktif", potongan: 65000 },
    { nama: "Ny. Nur Afnidah Mulia Swasta Iskandar", jabatan: "Anggota Bidang Sosial Budaya", kategori: "Istri PNS Aktif", noHp: "", alamat: "", status: "aktif", potongan: 65000 },
    { nama: "Ny. Vera Leonita Samosir Aston Marsito Doloksaribu", jabatan: "Anggota Bidang Sosial Budaya", kategori: "Istri PNS Aktif", noHp: "", alamat: "", status: "aktif", potongan: 65000 },
    { nama: "Ny. Deviyani Serevia Tarigan Erik P. A Depari", jabatan: "Anggota Bidang Sosial Budaya", kategori: "Istri PNS Aktif", noHp: "", alamat: "", status: "aktif", potongan: 65000 },
    { nama: "Ny. Sardah Batubara Herianto", jabatan: "Anggota Bidang Sosial Budaya", kategori: "Istri PNS Aktif", noHp: "", alamat: "", status: "aktif", potongan: 65000 },
    { nama: "Ny. Dewi Wulansari Khoirul Anwar Pulungan", jabatan: "Anggota Bidang Sosial Budaya", kategori: "Istri PNS Aktif", noHp: "", alamat: "", status: "aktif", potongan: 65000 },

    // === BELUM TERDAFTAR DI ABSENSI DW (58-77) - Istri Pensiunan ===
    { nama: "Ny. Oktipa Juyoko", jabatan: "Anggota Bidang Sosial Budaya", kategori: "Istri Pensiunan", noHp: "", alamat: "", status: "aktif", potongan: 65000 },
    { nama: "Ny. Mhd Faidillah", jabatan: "Anggota Bidang Sosial Budaya", kategori: "Istri Pensiunan", noHp: "", alamat: "", status: "aktif", potongan: 65000 },
    { nama: "Ny. Martahan Lubin Manurung", jabatan: "Anggota Bidang Sosial Budaya", kategori: "Istri Pensiunan", noHp: "", alamat: "", status: "aktif", potongan: 65000 },
    { nama: "Ny. Sangkot Sinaga", jabatan: "Anggota Bidang Sosial Budaya", kategori: "Istri Pensiunan", noHp: "", alamat: "", status: "aktif", potongan: 65000 },
    { nama: "Ny. T. Arif Munandar Harahap", jabatan: "Anggota Bidang Sosial Budaya", kategori: "Istri Pensiunan", noHp: "", alamat: "", status: "aktif", potongan: 65000 },
    { nama: "Ny. Timbul Pasaribu", jabatan: "Anggota Bidang Sosial Budaya", kategori: "Istri Pensiunan", noHp: "", alamat: "", status: "aktif", potongan: 65000 },
    { nama: "Ny. Ujur Anwar Banjarnahor", jabatan: "Anggota Bidang Sosial Budaya", kategori: "Istri Pensiunan", noHp: "", alamat: "", status: "aktif", potongan: 65000 },
    { nama: "Ny. Zulkarnain", jabatan: "Anggota Bidang Sosial Budaya", kategori: "Istri Pensiunan", noHp: "", alamat: "", status: "aktif", potongan: 65000 },
    { nama: "Ny. Moratua Janatama Purba", jabatan: "Anggota Bidang Sosial Budaya", kategori: "Istri Pensiunan", noHp: "", alamat: "", status: "aktif", potongan: 65000 },
    { nama: "Ny. Indra Syahnun Ritonga", jabatan: "Anggota Bidang Sosial Budaya", kategori: "Istri Pensiunan", noHp: "", alamat: "", status: "aktif", potongan: 65000 },
    { nama: "Ny. Imam Mahmuda Silalahi", jabatan: "Anggota Bidang Sosial Budaya", kategori: "Istri Pensiunan", noHp: "", alamat: "", status: "aktif", potongan: 65000 },
    { nama: "Ny. Harpansyah", jabatan: "Anggota Bidang Sosial Budaya", kategori: "Istri Pensiunan", noHp: "", alamat: "", status: "aktif", potongan: 65000 },
    { nama: "Ny. Fatan Danielow Sumbayak", jabatan: "Anggota Bidang Sosial Budaya", kategori: "Istri Pensiunan", noHp: "", alamat: "", status: "aktif", potongan: 65000 },
    { nama: "Ny. Gatot Handoyo", jabatan: "Anggota Bidang Sosial Budaya", kategori: "Istri Pensiunan", noHp: "", alamat: "", status: "aktif", potongan: 65000 },
    { nama: "Ny. Darwin Hutapea", jabatan: "Anggota Bidang Sosial Budaya", kategori: "Istri Pensiunan", noHp: "", alamat: "", status: "aktif", potongan: 65000 },
    { nama: "Ny. David Hasurungan Lumbantobing", jabatan: "Anggota Bidang Sosial Budaya", kategori: "Istri Pensiunan", noHp: "", alamat: "", status: "aktif", potongan: 65000 },
    { nama: "Ny. Benedictus Agung Sianipar", jabatan: "Anggota Bidang Sosial Budaya", kategori: "Istri Pensiunan", noHp: "", alamat: "", status: "aktif", potongan: 65000 },
    { nama: "Ny. Edi Iskandar", jabatan: "Anggota Bidang Sosial Budaya", kategori: "Istri Pensiunan", noHp: "", alamat: "", status: "aktif", potongan: 65000 },
    { nama: "Ny. Abdullah Ra'uf Isma", jabatan: "Anggota Bidang Sosial Budaya", kategori: "Istri Pensiunan", noHp: "", alamat: "", status: "aktif", potongan: 65000 },
    { nama: "Ny. Handi Zailani Nasution", jabatan: "Anggota Bidang Sosial Budaya", kategori: "Istri Pensiunan", noHp: "", alamat: "", status: "aktif", potongan: 65000 },

    // === PARTISIPAN (78-79) ===
    { nama: "Ny. Zunaidah Ibnu Alfi", jabatan: "Partisipan", kategori: "Partisipan Luar", noHp: "", alamat: "", status: "aktif", potongan: 0 },
    { nama: "Ny. Safrida Hanum Damanik Mhd Haffiz", jabatan: "Partisipan", kategori: "Partisipan Luar", noHp: "", alamat: "", status: "aktif", potongan: 0 },
];

// Default arisan settings
export const seedPengaturan = {
    periode: '12',
    iuranPerBulan: 65000,
    hadiahArisan: 0,
    tanggalMulai: '2025-01-01',
    tanggalBerakhir: '2025-12-31',
    periodeAktif: 'Periode 2025',
};
